# Generated by Django 4.1.6 on 2023-02-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("muti_user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="users/profile_pictures"
            ),
        ),
    ]
