# Generated by Django 4.1.6 on 2023-02-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("muti_user", "0003_alter_customuser_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="line",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="line1"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="pincode",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
