# Generated by Django 4.1.6 on 2023-02-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("muti_user", "0005_blogpost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
